{% set name = "rapidminer" %}
{% set version = "2026.0.1" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rapidminer-{{ version }}.tar.gz
  sha256: 14c3214ae61c1d7da08efa7c1bd63abf09180506bf8c266aedab38decf04b952

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - pandas >=2.2.0,<3.0.0
    - requests >=2.31.0,<3.0.0
    - numpy >=1.24.0,<3.0.0
    - zeep >=4.2.0,<5.0.0
    - h5py >=3.8.0,<4.0.0
    - cryptography >=41.0.0,<50.0.0
    - pyjwt >=2.8.0,<3.0.0

test:
  imports:
    - rapidminer
  commands:
    - pip check
    - python -c "import rapidminer; print('Version:', rapidminer.__version__)"
  requires:
    - pip

about:
  home: https://github.com/rapidminer/python-rapidminer
  summary: Tools for running RapidMiner processes and managing RapidMiner repositories.
  description: |
    This Python package allows you to interact with Altair AI Studio and Altair AI Hub.
    You can collaborate using the Altair AI repository and leverage the scalable 
    Altair AI Hub infrastructure to run processes.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://docs.rapidminer.com/
  dev_url: https://github.com/rapidminer/python-rapidminer

extra:
  recipe-maintainers:
    - tjarvas-altair
    - manojgit109
    - KartikCD
    - bullsoverbears
