{% set name = "rapidminer" %}
{% set version = "2025.1.0" %}
{% set python_min = "3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rapidminer-{{ version }}.tar.gz
  sha256: 58b6af810ef6f31344f156874a848c32f1c585ed8600dcfedb8fe339b0c99726

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=1
    - requests
    - numpy <2
    - zeep
    - h5py
    - cryptography
    - pyjwt

test:
  imports:
    - rapidminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rapidminer/python-rapidminer
  summary: Tools for running RapidMiner processes and managing RapidMiner repositories.
  license: AGPL-3.0-only
  license_file: LICENSE
  doc_url: https://docs.rapidminer.com/

extra:
  recipe-maintainers:
    - tjarvas-altair
    - manojgit109
    - KartikCD
    - bullsoverbears
