{% set name = "rapidminer" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidminer-{{ version }}.tar.gz
  sha256: 3b54a17777ad2269e3e8d98379a97bcec55dc809165f80d6868d6b52ea532514

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas >=1
    - requests
    - numpy <2
    - zeep
    - h5py
    - cryptography
    - pyjwt

test:
  imports:
    - rapidminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rapidminer/python-rapidminer
  summary: Tools for running RapidMiner processes and managing RapidMiner repositories.
  license: AGPL-3.0-only
  license_file: LICENSE
  doc_url: https://docs.rapidminer.com/

extra:
  recipe-maintainers:
    - gypataricza-altair
    - tjarvas-altair
